spring:
  application:
    name: store
  graphql:
    servlet:
      path: /graphql
    tools:
      schema-location-pattern: classpath:graphql/**/*.graphqls
  graphiql:
    endpoint: /graphql
    enabled: true
  datasource:
    url: jdbc:mysql://192.168.0.17:3306/store?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: 192.168.0.20:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: store-group
      auto-offset-reset: earliest
