package com.example.store.global.type;

public enum UpdateStoreType {
    STORE_NAME, STORE_ADDRESS, STORE_OPEN_AT,STORE_CLOSE_AT,STORE_PHONE,STORE_MINIMUM_ORDER_AMOUNT,STORE_INTRODUCTION, STORE_CATEGORY
}
